PREFIX tg: <https://example.org/tourguide#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?place ?name ?wd ?wdLabel ?instanceOfLabel
WHERE {
  ?place a tg:Place ;
         tg:name ?name ;
         owl:sameAs ?wd .
  FILTER(CONTAINS(STR(?wd), "wikidata.org/entity/Q"))

  SERVICE <https://query.wikidata.org/sparql> {
    ?wd <http://www.w3.org/2000/01/rdf-schema#label> ?wdLabel .
    FILTER(LANG(?wdLabel) = "fr")

    OPTIONAL {
      ?wd <http://www.wikidata.org/prop/direct/P31> ?instanceOf .
      ?instanceOf <http://www.w3.org/2000/01/rdf-schema#label> ?instanceOfLabel .
      FILTER(LANG(?instanceOfLabel) = "fr")
    }
  }
}
LIMIT 30
